Changed up test file to work with new organization

diff --git a/runTests b/runTests
--- a/runTests
+++ b/runTests
@@ -1,89 +1,72 @@
-#!/bin/bash
-KNODE="./knode"
+#!/bin/sh
 
-
-# Set time limit for all operations
-ulimit -t 30
-# Log file, file that contains a list of events which have been "logged" by a computer
-
-globallog=testall.log
-#remove file globallog , -f is for whether there is a file or not
-rm -f $globallog
-#errors
-error=0
-globalerror=0
-isTestingPass=0
-keep=0
-
-#error handling
-#always end if then else construct with a fi
-# $1 means first argument on command line
-SignalError() {
-if [ $error -eq 0 ] ; then
-error=1
-fi
-echo "$1" >> $globallog
+UPLINE=$(tput cuu1)
+ERASELINE=$(tput el)
+ERRORS=""
+TESTEDFILES=0
+ERRORCOUNT=0
+TESTINGSTRING=""
+PrepCounts() {
+  passFiles=(tests/*-pass.kn);
+  passFileCount=${#passFiles[@]};
+  failFiles=(tests/*-fail.kn);
+  failFileCount=${#failFiles[@]};
+  totalFiles=$((passFileCount+failFileCount));
+  echo "Commencing testing for $passFileCount passing tests and $failFileCount failing tests for $totalFiles total tests.\n";
 }
-
-# Run <args>
-# Report the command, run it, and report any errors
-Run() {
-#report into log if one faile or had an error
-echo $* >> $globallog
-#if the first command succeeds the second will not be evaluated
-eval $* || {
-SignalError "$1 failed on $*"
-return 1
-}
-}
-
-Check() {
-error=0
-basename=`echo $1 | sed 's/.*\\///
-s/.kn//'`
-basedir="`echo $1 | sed 's/\/[^\/]*$//'`/."
-echo -n "$basename..."
-echo >> $globallog
-echo "###### Testing $basename" >> $globallog
-rm -f "$1.out"
-Run "$KNODE" "$1" > "$1.out"
-# Report the status and clean up the generated files
-echo "Done testing"
-if [ $isTestingPass -eq 0 ] ; then
-  if [ $error -eq 0 ] ; then
-    echo -e "\033[32mOK\033[0m"
-    echo "###### SUCCESS" >> $globallog
+PrintStatus() {
+  echo "$ERASELINE$UPLINE$ERASELINE$UPLINE$ERASELINE\c"
+  if [ $TESTEDFILES -eq $totalFiles ]
+  then
+    if [ $ERRORCOUNT -gt 0 ]
+    then
+      echo "Testing Complete. Errors in $ERRORCOUNT of $TESTEDFILES tests."
+    else
+      echo "Testing Complete. No Errors."
+    fi
   else
-    echo -e "\033[31mFAILED\033[0m"
-    echo "###### FAILED" >> $globallog
-    globalerror=$error
+    echo "Testing \"$CURRENTFILE\" ($TESTEDFILES of $totalFiles)"
   fi
-else
-  if [ $error -eq 0 ] ; then
-    echo -e "\033[31mFAILED\033[0m"
-    echo "###### FAILED" >> $globallog
-  else
-    echo -e "\033[32mOK\033[0m"
-    echo "###### SUCCESS" >> $globallog
-    globalerror=$error
-  fi
-fi
+  echo $TESTINGSTRING
 }
-#Get all of the test scripts and store their names in $files
-passFiles="tests/*-pass.kn"
-failFiles="tests/*-fail.kn"
-
-#for each file in files, run them and print them to .out files
-echo -e "\033[36mNOW TESTING PASS FILES\033[0m"
-for f in $passFiles
+TestFile() {
+  tmperrors="$(./knode $CURRENTFILE 2>&1 >/dev/null)";
+  if [ $? -eq $1 ]
+  then
+    TESTINGSTRING+="\b\033[32m.\033[0m";
+  else
+    ERRORS="$ERRORS\n\033[34mIn file $CURRENTFILE:\033[0m\n$tmperrors\n";
+    ERRORCOUNT=$((ERRORCOUNT+1));
+    TESTINGSTRING+="\b\033[31mF\033[0m";
+  fi
+}
+PrepCounts
+for file in "${passFiles[@]}"
 do
-Check $f
+  TESTINGSTRING+="\033[33m.\033[0m"
+  CURRENTFILE=$file
+  TESTEDFILES=$((TESTEDFILES+1))
+  PrintStatus
+  TestFile 0
+  PrintStatus
 done
-isTestingPass=$(( $isTestingPass + 1 ))
-echo -e "\033[36mNOW TESTING FAIL FILES\033[0m"
-for f in $failFiles
+for file in "${failFiles[@]}"
 do
-Check $f
+  TESTINGSTRING+="\033[33m.\033[0m"
+  CURRENTFILE=$file
+  TESTEDFILES=$((TESTEDFILES+1))
+  PrintStatus
+  TestFile 1
+  PrintStatus
 done
-
-
+echo "$ERRORS"
+#for ((i = 0; i <= 50; i++))
+#do
+#for ((j = 0; j <= i; j++))
+#do
+#echo "=\c"
+#done
+#echo "\r\c"
+#sleep 1
+#done
+#echo ""
